config/routes.rb
Rails.application.routes.draw do

  get 'usuarios/new'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  get 'reservas/por_data' => 'reservas#por_data'
  get 'reservas/realizadas' => 'reservas#realizadas'
  get 'reservas/pagas' => 'reservas#pagas'
  get 'reservas/em_aberto' => 'reservas#em_aberto'
  get 'reservas/em_aberto_por_cliente/' => 'reservas#em_aberto_por_cliente'

  resources :perfis
  resources :profissionais
  resources :especialidades
  resources :servicos
  resources :clientes
  resources :reservas
  resources :usuarios

  root 'sessions#new'
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :reservas, dependent: :destroy
  validates :nome, :data_nascimento, :celular, :cep, :numero, :cidade, :bairro,
            :logradouro, :uf, presence: true
  validates :telefone, :celular, :cep, numericality: true, allow_blank: true
  validates :telefone, length: { is: 10 }, allow_blank: true
  validates :celular, length: { is: 11 }
  validates :cep, length: { is: 8 }
  validates :uf, length: { is: 2 }

  acts_as_paranoid
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[show edit update destroy]
  before_action :authorize

  def index
    @clientes = Cliente.order(:nome)
  end

  def show; end

  def new
    @cliente = Cliente.new if current_user.perfil_id != 3
  end

  def edit
    redirect_to clientes_path if current_user.perfil_id != 3
  end

  def create
    @cliente = Cliente.new(cliente_params)
    flash[:notice] = 'Cliente criado.' if current_user.perfil_id != 3 && @cliente.save
    respond_with(@cliente, location: @cliente)
  end

  def update
    flash[:notice] = 'Cliente atualizado.' if current_user.perfil_id != 3 && @cliente.update_attributes(cliente_params)
    respond_with(@cliente, location: @cliente)
  end

  def destroy
    flash[:notice] = 'Cliente excluído.' if current_user.perfil_id == 1 && @cliente.destroy
    respond_with(nil, location: clientes_url)
  end

  private

  def set_cliente
    @cliente = Cliente.find(params[:id])
  end

  def cliente_params
    params.require(:cliente).permit(:nome, :data_nascimento, :telefone,
                                    :celular, :email, :comentarios, :cep,
                                    :compl, :numero, :logradouro, :cidade,
                                    :bairro, :uf)
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
  <div class="col-md-12">
      <section "Cadastro">

        <%= simple_form_for(@cliente) do |f| %>
          <%= f.error_notification %>
          <div class="form-group">
            <div class="row">
              <div class="form-inputs">
                <div class="col-md-4 col-md-push-1">
                  <h3>Dados do Cliente</h3>
                  <%= f.input :nome, label: 'Nome' %>
                  <%= f.input :data_nascimento, label: 'Nascimento',
                              as: :date, html5: true %>
                  <%= f.input :telefone, label: 'Telefone' %>
                  <%= f.input :celular, label: 'Celular' %>
                  <%= f.input :email, label: 'Email' %>
                  <%= f.input :comentarios, label: 'Comentários' %>
                </div>

                <div class="col-md-4 col-md-push-3">
                  <h3>Endereço do Cliente</h3>
                  <%= f.input :cep, label: 'Cep',
                                    input_html: { id: 'cep',
                                                  size: '10', maxlength:'9',
                                                  onblur: 'pesquisacep(this.value);' } %>
                  <%= f.input :logradouro, label: 'Logradouro', readonly: true,
                                           input_html: { id: 'logradouro',
                                                         size: '60' } %>
                  <%= f.input :numero, label: 'Número' %>
                  <%= f.input :compl, label: 'Complemento' %>
                  <%= f.input :bairro, label: 'Bairro', readonly: true,
                                       input_html: { id: 'bairro', size: '40' } %>
                  <%= f.input :cidade, label: 'Cidade', readonly: true,
                                       input_html: { id: 'cidade', size: '40' } %>
                  <%= f.input :uf, label: 'UF', readonly: true, input_html: { id: 'uf',
                                                              size: 2,
                                                              maxlength: 2,
                                                              :style=> 'width: 50px' } %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="form-actions md-4 col-md-push-1">
                <%= f.button :submit, value: 'Salvar', :class => "btn btn-success"%>
                <%= link_to 'Voltar', clientes_path, :class => "btn btn-warning" %>
              </div>
            </div>

          </div>
        <% end %>

      </section>

  </div>

app/views/clientes/edit.html.erb
<div class="container" style="background-color:#DDE2E3">
  <div id="wrapper" style="text-align: center; color: black">
    <h1>Editar Cliente</h1>
  </div>

  <%= render 'form' %>

</div>

app/views/clientes/index.html.erb
<div class="container" style="color: black; text-align: center;">
  <p id="notice"><%= notice %></p>

  <h1> Clientes </h1>

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th style="text-align:center;font-size:16px">Nome</th>
          <th style="text-align:center;font-size:16px">Dt. Nascimento</th>
          <th style="text-align:center;font-size:16px">Telefone</th>
          <th style="text-align:center;font-size:16px">Celular</th>
          <th style="text-align:center;font-size:16px">Email</th>
          <th style="text-align:center;font-size:16px" colspan="3">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @clientes.each do |cliente| %>
          <tr>
            <td><%= cliente.nome %></td>
            <td><%= cliente.data_nascimento.strftime('%d/%m/%Y') %></td>
            <% if cliente.telefone.length > 0 %>
              <td><%= format_phone(cliente.telefone) %></td>
            <% else %>
              <td><%= %></td>
            <% end %>
            <% if cliente.celular.length > 0 %>
              <td><%= format_cell_phone(cliente.celular) %></td>
            <% else %>
              <td><%= %></td>
            <% end %>
            <td><%= cliente.email %></td>
            <td><%= link_to 'Exibir', cliente,
                                      :class => "btn btn-success" %></td>
            <% if current_user.perfil_id != 3 %>
              <td><%= link_to 'Editar', edit_cliente_path(cliente),
                                        :class => "btn btn-primary" %></td>
            <% end %>
            <% if current_user.perfil_id == 1 %>
            <td><%= link_to 'Excluir', cliente, method: :delete,
                                       data: { confirm: 'Tem certeza?' },
                                       :class => "btn btn-danger" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</br>

  <div class="form-actions" style="color: white">

    <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>
    <% if current_user.perfil_id != 3 %>
      <%= link_to 'Novo Cliente', new_cliente_path, :method => :get,
          :class => "btn btn-info" %>
    <% end %>

  </div>

</div>

app/views/clientes/new.html.erb
<div class="container" style="background-color:#DDE2E3">
  <div id="wrapper" style="text-align: center; color: black">
    <h1>Novo Cliente</h1>
  </div>

  <%= render 'form' %>


</div>

app/views/clientes/show.html.erb
<form>

  <div class="container" style="background-color:#C2DFE5">
    <div class="col-md-12">
      <div id="wrapper" style="text-align: center; color: black">
        <h2>Detalhes do Cliente</h2>
      </div>
      <section "Mensagem">
      <p id="notice" style="font-size:16px"><%= notice %></p>
    </section>
    <section "Cliente">
    <div class="col-md-4 col-md-push-1">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.nome">Nome: </label>
              <%= @cliente.nome %><br>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.data_nascimento">Nascimento: </label>
              <%= l(@cliente.data_nascimento, format: :simple) %><br>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.telefone">Telefone: </label>
              <% if @cliente.telefone.length > 0 %>
                <%= format_phone(@cliente.telefone) %>
              <% end %><br>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.celular">Celular: </label>
              <%= format_cell_phone(@cliente.celular) %>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.email">Email: </label>
              <% if @cliente.email.length > 0 %>
                <%= @cliente.email %>
              <% end %><br>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.comentarios">Comentários: </label>
              <%= @cliente.comentarios %><br>
            </div>
          </div>
        </div>
    </div>

    <div class="col-md-4 col-md-push-3">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.logradouro">Logradouro: </label>
              <%= @cliente.logradouro %><br>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.numero">Número: </label>
              <%= @cliente.numero %><br>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.compl">Complemento: </label>
              <% if @cliente.compl.length > 0 %>
                <%= @cliente.compl %>
              <% end %><br>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.cep">Cep: </label>
              <%= format_cep(@cliente.cep) %>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.bairro">Bairro: </label>
              <%= @cliente.bairro %>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@cliente.cidade">Cidade / UF: </label>
              <%= @cliente.cidade %> / <%= @cliente.uf %><br>
            </div>
          </div>
        </div>
    </div>

  </section>

  </div>
  <p><%= link_to 'Voltar', clientes_path, :class => "btn btn-warning" %></p>
</div>

</form>