config/routes.rb
Rails.application.routes.draw do

  get 'usuarios/new'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  get 'reservas/por_data' => 'reservas#por_data'
  get 'reservas/realizadas' => 'reservas#realizadas'
  get 'reservas/pagas' => 'reservas#pagas'
  get 'reservas/em_aberto' => 'reservas#em_aberto'
  get 'reservas/em_aberto_por_cliente/' => 'reservas#em_aberto_por_cliente'

  resources :perfis
  resources :profissionais
  resources :especialidades
  resources :servicos
  resources :clientes
  resources :reservas
  resources :usuarios

  root 'sessions#new'
end

app/models/especialidade.rb
class Especialidade < ApplicationRecord
  has_many :servicos, dependent: :destroy
  has_many :profissionais, dependent: :destroy
  validates :nome, presence: true, uniqueness: true
end

app/controllers/especialidades_controller.rb
class EspecialidadesController < ApplicationController
  before_action :set_especialidade, only: %i[show edit update destroy]
  before_action :authorize

  def index
    @especialidades = Especialidade.order(:nome)
  end

  def show; end

  def new
    @especialidade = Especialidade.new if current_user.perfil_id == 1
  end

  def edit
    redirect_to especialidades_path if current_user.perfil_id == 3
  end

  def create
    @especialidade = Especialidade.new(espec_params)
    flash[:notice] = 'Especialidade criada.' if current_user.perfil_id != 3 && @especialidade.save
    respond_with(@especialidade, location: @especialidade)
  end

  def update
    flash[:notice] = 'Especialidade atualizada.' if current_user.perfil_id != 3 && @especialidade.update_attributes(espec_params)
    respond_with(@especialidade, location: @especialidade)
  end

  def destroy
    flash[:notice] = 'Especialidade excluída.' if current_user.perfil_id == 1 && @especialidade.destroy
    respond_with(nil, location: especialidades_url)
  end

  private

  def set_especialidade
    @especialidade = Especialidade.find(params[:id])
  end

  def espec_params
    params.require(:especialidade).permit(:nome, :comentarios)
  end
end

app/helpers/especialidades_helper.rb
module EspecialidadesHelper
end

app/views/especialidades/_form.html.erb
<div class="col-md-12">

  <div class="col-md-4">

    <section "Cadastro">

      <%= simple_form_for(@especialidade) do |f| %>
        <%= f.error_notification %>
        <div class="form-group">

          <div class="form-inputs">
            <%= f.input :nome, label: 'Nome:' %>
            <%= f.input :comentarios, label: 'Comentários:' %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, value: 'Salvar', :class => "btn btn-success"%>
            <%= link_to 'Voltar', especialidades_path, :class => "btn btn-warning" %>
          </div>

        </div>
      <% end %>

    </section>


  </div>

  <div class="col-md-6">

    <section>
      <div class="col-md-4" style="margin:25px">
      </div>
    </section>

  </div>
</div>

app/views/especialidades/edit.html.erb
<div class="container" style="background-color:#DDE2E3">
  <div id="wrapper" style="text-align: center; color: black">
    <h1>Editar Especialidade</h1>
  </div>

  <%= render 'form' %>

</div>

app/views/especialidades/index.html.erb
<div class="container" style="color: black; text-align: center;">
  <p id="notice"><%= notice %></p>

  <h1> Especialidades </h1>

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th style="text-align:center;font-size:16px">Nome</th>
          <th style="text-align:center;font-size:16px">Comentários</th>
          <th style="text-align:center;font-size:16px" colspan="3">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @especialidades.each do |especialidade| %>
          <tr>
            <td><%= especialidade.nome %></td>
            <td><%= especialidade.comentarios %></td>
            <td><%= link_to 'Exibir', especialidade,
                                      :class => "btn btn-success" %></td>
            <% if current_user.perfil_id == 1 %>
              <td><%= link_to 'Editar', edit_especialidade_path(especialidade),
                                        :class => "btn btn-primary" %></td>
              <td><%= link_to 'Excluir', especialidade, method: :delete,
                                       data: { confirm: 'Tem certeza?' },
                                       :class => "btn btn-danger" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</br>

  <div class="form-actions" style="color: white">

    <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>
    <% if current_user.perfil_id != 3 %>
      <%= link_to 'Nova Especialidade', new_especialidade_path, :method => :get,
          :class => "btn btn-info" %>
    <% end %>

  </div>

</div>

app/views/especialidades/new.html.erb
<div class="container" style="background-color:#DDE2E3">
  <div id="wrapper" style="text-align: center; color: black">
    <h1>Nova Especialidade</h1>
  </div>

  <%= render 'form' %>


</div>

app/views/especialidades/show.html.erb
<form>

  <div class="container" style="background-color:#C2DFE5">
    <div class="col-md-12">
      <div id="wrapper" style="text-align: center; color: black">
        <h2>Detalhes da Especialidade</h2>
      </div>
      <section "Mensagem">
        <p id="notice" style="font-size:16px"><%= notice %></p>
      </section>
      <section "especialidade">
        <div class="col-md-4">
            <div class="row">
              <div class="col-md-12">
                <div class="form-group" style="font-size:16px">
                  <label for="@especialidade.nome">Nome: </label>
                  <%= @especialidade.nome %><br>
                </div>
                <div class="form-group" style="font-size:16px">
                  <label for="@especialidade.comentarios">Comentários: </label>
                  <%= @especialidade.comentarios %><br>
                </div>
              </div>
            </div>
        </div>

      </section>

    </div>

    <p><%= link_to 'Voltar', especialidades_path, :class => "btn btn-warning" %></p>
  </div>

</form>