config/routes.rb
Rails.application.routes.draw do

  get 'usuarios/new'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  get 'reservas/por_data' => 'reservas#por_data'
  get 'reservas/realizadas' => 'reservas#realizadas'
  get 'reservas/pagas' => 'reservas#pagas'
  get 'reservas/em_aberto' => 'reservas#em_aberto'
  get 'reservas/em_aberto_por_cliente/' => 'reservas#em_aberto_por_cliente'

  resources :perfis
  resources :profissionais
  resources :especialidades
  resources :servicos
  resources :clientes
  resources :reservas
  resources :usuarios

  root 'sessions#new'
end

app/models/reserva.rb
class Reserva < ApplicationRecord
  include ArelHelpers::ArelTable
  belongs_to :cliente
  belongs_to :servico
  belongs_to :profissional
  validates :cliente, :servico, :profissional, :data, :hora, presence: true

  accepts_nested_attributes_for :servico, reject_if: :all_blank,
                                          allow_destroy: true

  def self.search_by_month(mes, current_user)
    belongs_to :cliente
    belongs_to :profissional

    if Profissional?(current_user)
      Reserva.where("strftime('%m/%Y', data) = ? AND
                    realizado = ? AND profissional_id = ? AND pago = ?", mes,
                    false, current_user.profissional_id, false).order('data, hora ASC')
    else
      Reserva.where("strftime('%m/%Y', data) = ? AND
                    realizado = ? AND pago = ?", mes, false, false).order('data, hora ASC')
    end
    
  end

  def self.search_by_day(dia, current_user)
    belongs_to :cliente, -> { with_deleted }
    belongs_to :profissional, -> { with_deleted }
    if Profissional?(current_user)
      Reserva.where("strftime('%d/%m/%Y', data) = ? AND
                    realizado = ? AND profissional_id = ? AND pago = ?", dia,
                    false, current_user.profissional_id, false).order('data, hora ASC')
    else
      Reserva.where("strftime('%d/%m/%Y', data) = ? AND
                    realizado = ? AND pago = ?", dia, false, false).order('data, hora ASC')
    end
  end

  def self.search_by_realizadas(current_user)
    belongs_to :cliente, -> { with_deleted }
    belongs_to :profissional, -> { with_deleted }
    if Profissional?(current_user)
      Reserva.where('realizado = ? AND profissional_id = ? AND pago = ?', true,
                    current_user.profissional_id, false).order('data, hora ASC')
    else
      Reserva.where('realizado = ? AND pago = ?', true, false).order('data, hora ASC')
    end
  end

  def self.search_pagas(current_user)
    belongs_to :cliente, -> { with_deleted }
    belongs_to :profissional, -> { with_deleted }
    if Profissional?(current_user)
      Reserva.where('realizado = ? AND profissional_id = ? AND pago = ?', true,
                    current_user.profissional_id, true).order('data, hora ASC')
    else
      Reserva.where('realizado = ? AND pago = ?', true, true).order('data, hora ASC')
    end
  end

  def self.search_em_aberto
    belongs_to :cliente, -> { with_deleted }
    belongs_to :profissional, -> { with_deleted }

    Reserva.order(Arel.sql('clientes.nome')).joins(:cliente)
           .where('reservas.realizado = ? AND pago = ?', true, false)
           .group(:cliente_id)
           .pluck(:cliente_id, :nome, Arel.sql('COUNT(reservas.id) AS n_reserva,
                  SUM(reservas.preco) AS valor'))

  end

  def self.search_em_aberto_por_cliente(cliente)
    belongs_to :cliente, -> { with_deleted }
    belongs_to :profissional, -> { with_deleted }

    Reserva.order(Arel.sql('reservas.data')).joins(:cliente).joins(:servico)
           .joins(:profissional).where('reservas.realizado = ? AND
                                        reservas.pago = ? AND
                                        reservas.cliente_id = ?', true, false,
                                       cliente)
           .pluck(:id, Arel.sql('clientes.nome, profissionais.nome, reservas.data,
                  servicos.nome, reservas.preco'))
  end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: %i[show edit update destroy]
  before_action :authorize

  def index
    @date = params[:month] ? Date.parse(params[:month]) : Time.zone.today
    @reservas = Reserva.search_by_month(@date.strftime('%m/%Y'), current_user)
  end

  def show; end

  def por_data
    @date = params[:data] ? Date.parse(params[:data]) : Time.zone.today
    @reservas = Reserva.search_by_day(@date.strftime('%d/%m/%Y'), current_user)
  end

  def realizadas
    @reservas = Reserva.search_by_realizadas(current_user)
  end

  def em_aberto
    @reservas = Reserva.search_em_aberto
  end

  def em_aberto_por_cliente
    @cliente = params[:cliente_id]
    @reservas = Reserva.search_em_aberto_por_cliente(@cliente)
  end

  def pagas
    @reservas = Reserva.search_pagas(current_user)
  end

  def new
    @reserva = Reserva.new
    respond_with(@reserva, location: @reserva)
  end

  def edit; end

  def create
    @reserva = Reserva.new(reserva_params)
    @reserva.preco = @reserva.servico.try(:preco)
    flash[:notice] = 'Reserva criada.' if @reserva.save
    respond_with(@reserva, location: @reserva)
  end

  def update
    @reserva.preco = @reserva.servico.try(:preco)
    flash[:notice] = 'Reserva atualizada.' if @reserva.update_attributes(reserva_params)
    respond_with(@reserva, location: @reserva)
  end

  def destroy
    flash[:notice] = 'Reserva excluída.' if @reserva.destroy
    respond_with(nil, location: reservas_url)
  end

  private

  def set_reserva
    @reserva = Reserva.find(params[:id])
  end

  def reserva_params
    params.require(:reserva).permit(:cliente_id, :reserva_id, :profissional_id,
                                    :data, :hora, :comentarios, :realizado,
                                    :pago, :preco, :servico_id)
  end
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/reservas/_form.html.erb
<div class="col-md-12">
  <%= simple_form_for @reserva, html: { multipart: true } do |f| %>
    <%= f.error_notification %>
    <div class="panel">
      <div class="col-md-6">

        <div class="form-group">
              <% if current_user.perfil_id == 3 %>
                <%= f.association :cliente, label: 'Cliente:', label_method: :nome,
                                  value_method: :id, disabled: true %>
              <% else %>
                <%= f.association :cliente, label: 'Cliente:', label_method: :nome,
                                  value_method: :id %>
              <% end %>
              <%= f.association :servico, label: 'Serviço:', label_method: :nome,
                                value_method: :id %>
              
              <% if current_user.perfil_id == 3 %>
                <%= f.association :profissional, label: 'Profissional:',
                                  label_method: :nome, value_method: :id, disabled: true %>
              <% else %>
                <%= f.association :profissional, label: 'Profissional:',
                                  label_method: :nome, value_method: :id %>
              <% end %>
              <%= f.input :data, label: 'Data:', as: :date, html5: true %>
              <%= f.input :hora, label: 'Hora:' , as: :time, html5: true %>
              <%= f.input :comentarios, label: 'Comentários:' %>
              <%= f.input :realizado, label: 'Realizado:', as: :boolean %>

              <%= f.button :submit, value: 'Cadastrar' %>

              <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>
              </div>
          </div>
        </div>
      <% end %>
  </div>

app/views/reservas/edit.html.erb
<div class="container" style="background-color:#C2DFE5">
  <div class="col-md-12">
    <div id="wrapper" style="text-align: center; color: black">
      <h1>Editar Reserva</h1>
    </div>

    <section "Reserva">
      <div class="col-md-4 col-md-push-4">

        <%= simple_form_for @reserva, html: { multipart: true,
                                  :class => 'form-vertical' } do |f| %>

          <%= f.error_notification %>

          <div class="form-group">
            <div class="row">
              <%= f.association :cliente, label: 'Cliente:', label_method: :nome,
                                value_method: :id, disabled: true %>
            </div>
            <div class="row">
              <%= f.association :servico, label: 'Serviço:', label_method: :nome,
                                value_method: :id %>
            </div>
            <div class="row">
              <%= f.association :profissional, label: 'Profissional:',
                                label_method: :nome, value_method: :id %>
            </div>
            <div class="row">
              <%= f.input :data, label: 'Data:', as: :date, html5: true %>
            </div>
            <div class="row">
              <%= f.input :hora, label: 'Hora:' , as: :time, html5: true %>
            </div>
            <div class="row">
              <%= f.input :comentarios, label: 'Comentários:' %>
            </div>
            <div class="row">
              <div class="col-md-6">
                <%= f.input :realizado, label: 'Realizado', as: :boolean %>
              </div>
              <div class="col-md-6">
                <%= f.input :pago, label: 'Pago', as: :boolean %>
              </div>
            </div>

            <%= f.button :submit, value: 'Salvar', :class => "btn btn-success" %>
            <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>
          </div>

        <% end %>
      </div>
    </section>

  </div>
</div>

app/views/reservas/em_aberto.html.erb
<div class="container" style="color: black; text-align: center;">
  <p id="notice"><%= notice %></p>

  <h1>Reservas Em Aberto </h1>

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th style="text-align:center;font-size:16px">Cliente</th>
          <th style="text-align:center;font-size:16px">Qtd. Reservas</th>
          <th style="text-align:center;font-size:16px">Valor</th>
          <th style="text-align:center;font-size:16px" colspan="2">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @reservas.each do |reserva| %>
          <tr>
            <td><%= reserva[1] %></td>
            <td><%= reserva[2] %></td>
            <td><%= number_to_currency(reserva[3], locale: 'pt-BR') %></td>

            <td><%= link_to 'Visualizar',
                            reservas_em_aberto_por_cliente_path(cliente_id: reserva[0]),
                            :class => "btn btn-primary" %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="form-actions" style="color: white">

    <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>

  </div>

</div>

app/views/reservas/em_aberto_por_cliente.html.erb
<div class="container" style="color: black; text-align: center;">
  <p id="notice"><%= notice %></p>

  <h1>Reservas Em Aberto do Cliente </h1>

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th style="text-align:center;font-size:16px">Cliente</th>
          <th style="text-align:center;font-size:16px">Profissional</th>
          <th style="text-align:center;font-size:16px">Data</th>
          <th style="text-align:center;font-size:16px">Serviço</th>
          <th style="text-align:center;font-size:16px">Valor</th>
        </tr>
      </thead>

      <tbody>
        <% @reservas.each do |reserva| %>
          <tr>
            <td><%= reserva[1] %></td>
            <td><%= reserva[2] %></td>
            <td><%= reserva[3].strftime('%d/%m/%Y') %></td>
            <td><%= reserva[4] %></td>
            <td><%= number_to_currency(reserva[5], locale: 'pt-BR') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</br>

  <div class="form-actions" style="color: white">

    <%= link_to 'Voltar', reservas_em_aberto_path, :class => "btn btn-warning" %>

  </div>

</div>

app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <div class="well well-lg" style="color: black; text-align: center">

    <h1>Reservas</h1>

    <div id="divVisualizacao" style="color: blue; text-align: center">
      <h4>Escolha a Visualização das Reservas</h4>
      <h5><label><input id="calendar" value="calendar" name="vizualizacao" type="checkbox" checked onClick="toggle('calendar');"> Calendário</label>
      <label><input id="divTabela" value="divTabela" name="vizualizacao" type="checkbox" checked onClick="toggle('divTabela');"> Tabela</label></h5>

      <h2 id="month">
    		<%= link_to "<", month: (@date.beginning_of_month-1).strftime("%b%Y") %>
    		<%= I18n.l @date, format: :mes_ano, locale: 'pt-BR' %>
    		<%= link_to ">", month: (@date.end_of_month+1).strftime("%b%Y") %>
    	</h2>

    </div>

    <div id="calendar">

    	<%= calendar_for @reservas, year: @date.year, month: @date.month do |t| %>
    	 <%= t.head('DOM','SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB') %>
    	 <%= t.day(day_method: :data) do |day, reservas| %>
    	  <%= link_to day.strftime('%d/%m/%Y'),
                    reservas_por_data_path(:data => day.strftime('%d/%m/%Y')) %>
        <br />

    	  <% reservas.each do |reserva| %>
    	   <%= link_to h(reserva.cliente.nome),reserva %><br>
         <%= h(reserva.servico.nome) %><br>
         <%= h(l(reserva.hora,format: :simple_time)) %><br><br>
    	  <% end %>
    	 <% end %>
    	<% end %>
    </div>
    <br />
    <div id="divTabela" class="table-responsive">

      <table class="table table-bordered">
        <thead>
          <tr>
            <th style="text-align:center;font-size:16px;color: #A11">Data</th>
            <th style="text-align:center;font-size:16px;color: #A11">Hora</th>
            <th style="text-align:center;font-size:16px;color: #A11">Cliente</th>
            <th style="text-align:center;font-size:16px;color: #A11">Serviço</th>
            <th style="text-align:center;font-size:16px;color: #A11">Profissional</th>
            <th style="text-align:center;font-size:16px;color: #A11" colspan="3">Ações</th>
          </tr>
        </thead>

        <tbody>
          <% @reservas.each do |reserva| %>
            <tr>
              <td><%= reserva.data.strftime('%d/%m/%Y') %></td>
              <td><%= reserva.hora.strftime('%H:%M') %></td>
              <td><%= reserva.cliente.nome %></td>
              <td><%= reserva.servico.nome %></td>
              <td><%= reserva.profissional.nome %></td>
              <td><%= link_to 'Exibir', reserva,
                                        :class => "btn btn-success" %></td>
              <td><%= link_to 'Editar', edit_reserva_path(reserva),
                                        :class => "btn btn-primary" %></td>
              <td><%= link_to 'Excluir', reserva, method: :delete,
                                         data: { confirm: 'Tem certeza?' },
                                         :class => "btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <br>

    <div class="form-actions" style="color: white">
        <% if current_user.perfil_id != 3 %>
          <%= link_to 'Nova Reserva', new_reserva_path, :method => :get,
              :class => "btn btn-info" %>
        <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
function toggle(divId) {
  var divArray = document.getElementsByTagName("div");
  for(i = 0; i < divArray.length; i++){
      if(divArray[i].id == divId){
          if(divArray[i].style.display != 'none'){
              divArray[i].style.display = 'none';
          }else{
              divArray[i].style.display = '';
          }
      }
  }
}
</script>

app/views/reservas/new.html.erb
<div class="container" style="background-color:#C2DFE5">
  <div class="col-md-12">
    <div id="wrapper" style="text-align: center; color: black">
      <h1>Nova Reserva</h1>
    </div>
    <div class="row">

      <div class="col-md-4 col-md-push-4">
        <section "Reserva">

          <%= simple_form_for @reserva, html: { multipart: true,
                                    :class => 'form-vertical' } do |f| %>

            <%= f.error_notification %>

            <div class="form-group">
              <div class="row">
                <%= f.association :cliente, label: 'Cliente:', label_method: :nome,
                                  value_method: :id %>
              </div>
              <div class="row">
                <%= f.association :servico, label: 'Serviço:', label_method: :nome,
                                  value_method: :id %>
              </div>
              <div class="row">
                <%= f.association :profissional, label: 'Profissional:',
                                  label_method: :nome, value_method: :id %>
              </div>
              <div class="row">
                <%= f.input :data, label: 'Data:', as: :date, html5: true %>
              </div>
              <div class="row">
                <%= f.input :hora, label: 'Hora:' , as: :time, html5: true %>
              </div>
              <div class="row">
                <%= f.input :comentarios, label: 'Comentários:' %>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <%= f.input :realizado, label: 'Realizado', as: :boolean %>
                </div>
                <div class="col-md-6">
                  <%= f.input :pago, label: 'Pago', as: :boolean %>
                </div>
              </div>

              <%= f.button :submit, value: 'Salvar', :class => "btn btn-success" %>
              <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>
            </div>

          <% end %>
        </section>
      </div>

    </row>


    </div>
  </div>

app/views/reservas/pagas.html.erb
<div class="container" style="color: black; text-align: center;">
  <p id="notice"><%= notice %></p>

  <h1>Reservas Pagas </h1>

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th style="text-align:center;font-size:16px">Data</th>
          <th style="text-align:center;font-size:16px">Hora</th>
          <th style="text-align:center;font-size:16px">Cliente</th>
          <th style="text-align:center;font-size:16px">Serviço</th>
          <th style="text-align:center;font-size:16px">Valor</th>
          <th style="text-align:center;font-size:16px">Profissional</th>
          <th style="text-align:center;font-size:16px" colspan="3">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @reservas.each do |reserva| %>
          <tr>
            <td><%= reserva.data.strftime('%d/%m/%Y') %></td>
            <td><%= reserva.hora.strftime('%H:%M') %></td>
            <td><%= reserva.cliente.nome %></td>
            <td><%= reserva.servico.nome %></td>
            <td><%= number_to_currency(reserva.servico.preco, locale: 'pt-BR') %></td>
            <td><%= reserva.profissional.nome %></td>
            <td><%= link_to 'Exibir', reserva,
                                      :class => "btn btn-success" %></td>
            
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</br>

  <div class="form-actions" style="color: white">

    <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>
    <% if current_user.perfil_id != 3 %>
      <%= link_to 'Nova Reserva', new_reserva_path, :method => :get,
          :class => "btn btn-info" %>
    <% end %>

  </div>

</div>

app/views/reservas/por_data.html.erb
<div class="container" style="color: black; text-align: center;">
  <p id="notice"><%= notice %></p>

  <h1>Reservas Do Dia  - <%= @date.strftime('%d/%m/%Y') %></h1>

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th style="text-align:center;font-size:16px">Data</th>
          <th style="text-align:center;font-size:16px">Hora</th>
          <th style="text-align:center;font-size:16px">Cliente</th>
          <th style="text-align:center;font-size:16px">Serviço</th>
          <th style="text-align:center;font-size:16px">Profissional</th>
          <th style="text-align:center;font-size:16px">Comentários</th>
          <th style="text-align:center;font-size:16px" colspan="3">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @reservas.each do |reserva| %>
          <tr>
            <td><%= reserva.data.strftime('%d/%m/%Y') %></td>
            <td><%= reserva.hora.strftime('%H:%M') %></td>
            <td><%= reserva.cliente.nome %></td>
            <td><%= reserva.servico.nome %></td>
            <td><%= reserva.profissional.nome %></td>
            <td><%= reserva.comentarios %></td>
            <td><%= link_to 'Exibir', reserva,
                                      :class => "btn btn-success" %></td>
            <td><%= link_to 'Editar', edit_reserva_path(reserva),
                                      :class => "btn btn-primary" %></td>
            <td><%= link_to 'Excluir', reserva, method: :delete,
                                       data: { confirm: 'Tem certeza?' },
                                       :class => "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</br>

  <div class="form-actions" style="color: white">

    <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>
    <% if current_user.perfil_id != 3 %>
      <%= link_to 'Nova Reserva', new_reserva_path, :method => :get,
          :class => "btn btn-info" %>
    <% end %>

  </div>

</div>

app/views/reservas/realizadas.html.erb
<div class="container" style="color: black; text-align: center;">
  <p id="notice"><%= notice %></p>

  <h1>Serviços Realizados </h1>

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th style="text-align:center;font-size:16px">Data</th>
          <th style="text-align:center;font-size:16px">Hora</th>
          <th style="text-align:center;font-size:16px">Cliente</th>
          <th style="text-align:center;font-size:16px">Serviço</th>
          <th style="text-align:center;font-size:16px">Profissional</th>
          <th style="text-align:center;font-size:16px">Comentários</th>
          <th style="text-align:center;font-size:16px" colspan="3">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @reservas.each do |reserva| %>
          <tr>
            <td><%= reserva.data.strftime('%d/%m/%Y') %></td>
            <td><%= reserva.hora.strftime('%H:%M') %></td>
            <td><%= reserva.cliente.nome %></td>
            <td><%= reserva.servico.nome %></td>
            <td><%= reserva.profissional.nome %></td>
            <td><%= reserva.comentarios %></td>
            <td><%= link_to 'Exibir', reserva,
                                      :class => "btn btn-success" %></td>
            <td><%= link_to 'Editar', edit_reserva_path(reserva),
                                      :class => "btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</br>

  <div class="form-actions" style="color: white">

    <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>

  </div>

</div>

app/views/reservas/show.html.erb
<form>
  <div class="container" style="background-color:#C2DFE5">
    <div class="row">
      <div class="col-md-12">
        <div id="wrapper" style="text-align: center; color: black">
         <h2>Detalhes da Reserva</h2>
        </div>

        <section "Reserva">
          <section "Mensagem">
            <p id="notice" style="font-size:16px"><%= notice %></p>
          </section>

          <div class="col-md-4 col-md-push-4">
            <div class="row">
              <div class="col-md-12" style="font-size:16px">
                <label for="@reserva.cliente.nome">Cliente: </label>
                <%= @reserva.cliente.nome %><br>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12" style="font-size:16px">
                <label for="@reserva.servico.nome">Serviço: </label>
                <%= @reserva.servico.nome %><br>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12" style="font-size:16px">
                <label for="@reserva.profissional.nome">Profissional: </label>
                <%= @reserva.profissional.nome %><br>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12" style="font-size:16px">
                <label for="@reserva.preco">Preço: </label>
                <%= number_to_currency(@reserva.preco, locale: 'pt-BR') %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12" style="font-size:16px">
                <label for="@reserva.data">Data: </label>
                <%= l(@reserva.data, format: :simple) %><br>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12" style="font-size:16px">
                <label for="@reserva.hora">Hora: </label>
                <%= l(@reserva.hora, format: :simple_time) %><br>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12" style="font-size:16px">
                <label for="@reserva.comentarios">Comentários: </label>
                <%= @reserva.comentarios %><br>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6" style="font-size:16px">
                <label for="@reserva.realizado">Realizado: </label>
                <% if @reserva.realizado %>
                  <%= 'Sim' %>
                <% else %>
                  <%= 'Não' %>
                <% end %>
              </div>
              <div class="col-md-6" style="font-size:16px">
                <label for="@reserva.pago">Pago: </label>
                <% if @reserva.pago %>
                  <%= 'Sim' %>
                <% else %>
                  <%= 'Não' %>
                <% end %>
              </div>
            </div>

            <div class="form-actions" style="color: white">
              <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>
              <% if !@reserva.pago %>
                <%= link_to 'Editar', edit_reserva_path(@reserva),
                            :class => "btn btn-primary" %>
                <%= link_to 'Excluir', @reserva, method: :delete,
                            data: { confirm: 'Tem certeza?' },
                            :class => "btn btn-danger" %>
              <% end %>

            </div>

          </div>

        </section>
      </div>
    </div>
  </div>

</form>