config/routes.rb
Rails.application.routes.draw do

  get 'usuarios/new'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  get 'reservas/por_data' => 'reservas#por_data'
  get 'reservas/realizadas' => 'reservas#realizadas'
  get 'reservas/pagas' => 'reservas#pagas'
  get 'reservas/em_aberto' => 'reservas#em_aberto'
  get 'reservas/em_aberto_por_cliente/' => 'reservas#em_aberto_por_cliente'

  resources :perfis
  resources :profissionais
  resources :especialidades
  resources :servicos
  resources :clientes
  resources :reservas
  resources :usuarios

  root 'sessions#new'
end

app/models/servico.rb
class Servico < ApplicationRecord
  belongs_to :especialidade
  has_many :reservas, dependent: :destroy
  validates :nome, :especialidade, :tempo_estimado, :preco, presence: true
  validates :tempo_estimado, :preco, numericality: true, allow_blank: true
end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
  before_action :set_servico, only: %i[show edit update destroy]
  before_action :authorize

  def index
    @servicos = Servico.order(:nome)
  end

  def show; end

  def new
    @servico = Servico.new if current_user.perfil_id == 1
  end

  def edit
    redirect_to reservas_path if current_user.perfil_id == 3
  end

  def create
    @servico = Servico.new(servico_params)
    flash[:notice] = 'Serviço  criado.' if current_user.perfil_id != 3 && @servico.save
    respond_with(@servico, location: @servico)
  end

  def update
    flash[:notice] = 'Serviço atualizado.' if current_user.perfil_id != 3 && @servico.update_attributes(servico_params)
    respond_with(@servico, location: @servico)
  end

  def destroy
    flash[:notice] = 'Serviço  excluído.' if current_user.perfil_id == 1 && @servico.destroy
    respond_with(nil, location: servicos_url)
  end

  private

  def set_servico
    @servico = Servico.find(params[:id])
  end

  def servico_params
    params.require(:servico).permit(:nome, :especialidade_id, :tempo_estimado,
                                    :preco, :descricao)
  end
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/views/servicos/_form.html.erb
  <div class="col-md-12">

    <div class="col-md-4">

      <section "Cadastro">

        <%= simple_form_for(@servico) do |f| %>
          <%= f.error_notification %>
          <div class="form-group">

            <div class="form-inputs">
              <%= f.input :nome, label: 'Nome:' %>
              <%= f.association :especialidade, label: 'Especialidade:',
                                label_method: :nome, value_method: :id %>
              <%= f.input :tempo_estimado, label: 'Tempo Estimado:' %>
              <%= f.input :preco, label: 'Preço:' %>
              <%= f.input :descricao, label: 'Descrição:' %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, value: 'Salvar', :class => "btn btn-success"%>
              <%= link_to 'Voltar', servicos_path, :class => "btn btn-warning" %>
            </div>

          </div>
        <% end %>

      </section>


    </div>

    <div class="col-md-6">

      <section>
        <div class="col-md-4" style="margin:25px">
        </div>
      </section>

    </div>
  </div>

app/views/servicos/edit.html.erb
<div class="container" style="background-color:#DDE2E3">
  <div id="wrapper" style="text-align: center; color: black">
    <h1>Editar Serviço</h1>
  </div>

  <%= render 'form' %>

</div>

app/views/servicos/index.html.erb
<div class="container" style="color: black; text-align: center;">
  <p id="notice"><%= notice %></p>

  <h1> Serviços </h1>

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th style="text-align:center;font-size:16px">Nome</th>
          <th style="text-align:center;font-size:16px">Especialidade</th>
          <th style="text-align:center;font-size:16px">Tempo Estimado</th>
          <th style="text-align:center;font-size:16px">Preço</th>
          <th style="text-align:center;font-size:16px" colspan="3">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @servicos.each do |servico| %>
          <tr>
            <td><%= servico.nome %></td>
            <td><%= servico.especialidade.nome %></td>
            <td><%= servico.tempo_estimado %> minuto(s)</td>
            <td><%= number_to_currency(servico.preco, locale: 'pt-BR') %></td>
            <td><%= link_to 'Exibir', servico,
                                      :class => "btn btn-success" %></td>
            <% if current_user.perfil_id != 3 %>
              <td><%= link_to 'Editar', edit_servico_path(servico),
                                       :class => "btn btn-primary" %></td>
            <% end %>
            <% if current_user.perfil_id == 1 %>
              <td><%= link_to 'Excluir', servico, method: :delete,
                                         data: { confirm: 'Tem certeza?' },
                                         :class => "btn btn-danger" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</br>

  <div class="form-actions" style="color: white">

    <%= link_to 'Voltar', reservas_path, :class => "btn btn-warning" %>
    <% if current_user.perfil_id == 1 %>
      <%= link_to 'Novo servico', new_servico_path, :method => :get,
          :class => "btn btn-info" %>
    <% end %>

  </div>

</div>

app/views/servicos/new.html.erb
<div class="container" style="background-color:#DDE2E3">
  <div id="wrapper" style="text-align: center; color: black">
    <h1>Novo Serviço</h1>
  </div>

  <%= render 'form' %>


</div>

app/views/servicos/show.html.erb
<form>

  <div class="container" style="background-color:#C2DFE5">
    <div class="col-md-12">
      <div id="wrapper" style="text-align: center; color: black">
        <h2>Detalhes do Serviço</h2>
      </div>
      <section "Mensagem">
      <p id="notice" style="font-size:16px"><%= notice %></p>
    </section>
    <section "servico">
    <div class="col-md-4">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group" style="font-size:16px">
              <label for="@servico.nome">Nome: </label>
              <%= @servico.nome %><br>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@servico.especialidade.nome">Especialidade: </label>
              <%= @servico.especialidade.nome %><br>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@servico.tempo_estimado">Tempo Estimado: </label>
              <%= @servico.tempo_estimado %>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@servico.preco">Preço: </label>
              <%= number_to_currency(@servico.preco, locale: 'pt-BR') %>
            </div>
            <div class="form-group" style="font-size:16px">
              <label for="@servico.descricao">Descrição: </label>
              <% if @servico.descricao.length > 0 %>
                <%= @servico.descricao %>
              <% end %><br>
            </div>
          </div>
        </div>
    </div>

  </section>

</div>
<p><%= link_to 'Voltar', servicos_path, :class => "btn btn-warning" %></p>
</div>

</form>